I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script call
    call ch0
  File "game/script.rpy", line 103, in script
    show sayori at t11
  File "game/script.rpy", line 103, in <module>
    show sayori at t11
NameError: name 't11' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script call
    call ch0
  File "game/script.rpy", line 103, in script
    show sayori at t11
  File "renpy/ast.py", line 1191, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1150, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 103, in <module>
    show sayori at t11
NameError: name 't11' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
DDLC 1.0
Fri May  7 23:28:28 2021
